### ISSUE TITLE
Build 138680 - 13/12/22 - Failed To Inject Hook 6

### ISSUE THREAD

**Issue by TheWhiteWolves** [Krappa322/arcdps_unofficial_extras_releases#12]
Latest patch for today broke it again, getting hook 6 failing to inject again.

![image](https://user-images.githubusercontent.com/1471503/207430718-ee0b0a57-6dc3-4792-bcd6-34269679ac1b.png)

**Comment by knoxfighter** [comment]
Fix in release candidate.
