### ISSUE TITLE
Initialization failed -- Reasons 6, 7, 8

### ISSUE THREAD

**Issue by ebahonounazumi** [Krappa322/arcdps_unofficial_extras_releases#16]
![nshRprX](https://user-images.githubusercontent.com/89506006/233214870-0872a7cf-719c-4a02-b046-5a8ef701f364.jpeg)

Whenever loading GW2, Unofficial Extras window shows:

Initialization Failed. Reasons given: 
Failed to inject hook 6
Failed to inject hook 7
Failed to inject hook 8

I'm not sure what it breaks in total, but it breaks the presets function (I used this for settings presets ie. WvW settings preset & PvE settings preset, not keybinds unfortunately)

![v3rpCuw](https://user-images.githubusercontent.com/89506006/233215337-3f1db28a-6f25-49ef-88b6-a6c089e3e7c1.jpeg)

**Comment by knoxfighter** [comment]
Already fixed with the latest pre-release. I will create a proper release this evening.

About KeyBind-Presets: You can use the gw2 internal system. Or you can activate automatic loading by arcdps, since that was implemented, i removed the keybind presets feature from unofficial extras :)
