### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by AstanVizu** [Krappa322/arcdps_unofficial_extras_releases#2]
Hi,
I just installed the addon and I somehow cannot figure out how to use it.
It seems to be installed correctly, since the Extensions tab of arcdps shows a tab "unofficial_extras" and the "killproof.me" addon doesn't complain anymore about the addon missing.
However, that's it. I cannot see any other functionality of the addon.
Thanks!
Edit: I understand that this addon is only meant to provide additional data to other addons.
I would like to use the functionality mentioned on the start page:

    When players leave or join the party/squad
    What role a player has in the squad
    What subgroup a player is in
    If the player is ready or not (in a squad ready check)

Which arcdps addons do I have to install to see these things?

Thanks!

**Comment by Krappa322** [comment]
The killproof addon uses these. If you join a party or squad you should immediately see all players, regardless of what instance they are in :)

**Comment by AstanVizu** [comment]
I would like to use the addon to manage squads as a commander. For this, I would like to assign roles to players (Druid, Alac, BS, etc.) and see who recently joined or left the squad.
Is this possible through the killproof addon?
Your addon seems to be perfect for doing this.

**Comment by Krappa322** [comment]
That's not possible through the killproof addon. I have had some ideas like what you are talking about, but none of it materialized (and probably not likely to be for some time). Sadly my time is limited :(
