### ISSUE TITLE
Failed to inject hook 6,7,8 and 12

### ISSUE THREAD

**Issue by justgalak** [Krappa322/arcdps_unofficial_extras_releases#20]
This happens after the last update ( Build 152165 ) and with the most recent release of ArcDPS.

**Comment by Sereath** [comment]
Yeah same here:
![image](https://github.com/Krappa322/arcdps_unofficial_extras_releases/assets/54506307/2b60af9b-ac40-454a-b0d8-cc5a40bd023f)

**Comment by knoxfighter** [comment]
That is expected, i am already working on a fix.
KeyBind exports/callbacks and GraphicSettingsPresets are disabled.

**Comment by DRN88** [comment]
Hey. Thanks for the plugin. May I ask, is there still no update?

**Comment by knoxfighter** [comment]
I have created a pre-release yesterday and will make it a proper release later tonight :)

**Comment by justgalak** [comment]
Thanks for the fix and the addon, really missed those additional features. ❤️
