### ISSUE TITLE
Failed to inject hook 12

### ISSUE THREAD

**Issue by Jiblet** [Krappa322/arcdps_unofficial_extras_releases#22]
Getting this as of 2024-03-25 GW2 client build, thanks!

**Comment by Sereath** [comment]
Same.
![image](https://github.com/Krappa322/arcdps_unofficial_extras_releases/assets/54506307/39436136-b551-4cb9-91ad-dbdde4f870cd)

**Comment by knoxfighter** [comment]
This disables keybind callbacks and exported functions. I will release an update later this week.

**Comment by lvxku** [comment]
Thank you for your time and work on this btw on behalf of all the players struggling with the mouse cursor/camera turning bug

**Comment by WolfSabian** [comment]
> Thank you for your time and work on this btw on behalf of all the players struggling with the mouse cursor/camera turning bug

Wait... what exactly is causing this? I've been assuming it's just been hair or something interfering with my mouse. I haven't looked into it beyond that.

And yes, thank you Knox. I look forward to the update.

**Comment by knoxfighter** [comment]
@WolfSabian gw2 does not lock your mouse while it is invisible, sometimes it fails to reset the mouse position when it gets visible again. Also it is possible to interact with e.g. the minimap while the mouse is invisible. I added a mouse lock feature so the mouse does not move anymore when it is invisible.

**Comment by WolfSabian** [comment]
> @WolfSabian gw2 does not lock your mouse while it is invisible, sometimes it fails to reset the mouse position when it gets visible again. Also it is possible to interact with e.g. the minimap while the mouse is invisible. I added a mouse lock feature so the mouse does not move anymore when it is invisible.

Gotcha, thanks for the info.
