### ISSUE TITLE
Game crashes (25-04-2024)

### ISSUE THREAD

**Issue by Eremoo** [Krappa322/arcdps_unofficial_extras_releases#23]
Game crashes when loading into the world. This to say that it starts fine and makes it to the character selection screen.
Removing this from the gw2 folder fixes the crashing so I'm assuming this is the issue

**Comment by BonSie** [comment]
Same issue, seems to be caused by the keybind feature. If you disable it before the first character load you can reactivate it after, but if you don't it crashes.

**Comment by knoxfighter** [comment]
This is caused by multiboxing and other issues with the mumble link. It is a pre-release for a reason and i am working on a fix :)
