### ISSUE TITLE
[bug] "disable keybinds messages" also hide emotes

### ISSUE THREAD

**Issue by hurricanerainbow** [Krappa322/arcdps_unofficial_extras_releases#24]
Sounds weird, but whenever that's enabled, can't see emote action text in chat anymore.

![image_2024-05-18_143906625](https://github.com/Krappa322/arcdps_unofficial_extras_releases/assets/68096/d7887dcc-29eb-47bb-962a-05a3e0790dcc)

clip of a screenshot taken with the checkbox unchecked and the emote showing.

![image_2024-05-18_144157401](https://github.com/Krappa322/arcdps_unofficial_extras_releases/assets/68096/bda8f64e-acca-4301-843e-13e761a4eed8)

same /dance but with it enabled. no emote text. yeah re-did the animation :).

**Comment by knoxfighter** [comment]
Fixed in [Release 1.18.rc7](https://github.com/Krappa322/arcdps_unofficial_extras_releases/releases/tag/v1.18.rc7)
