### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by bolb** [Krappa322/arcdps_unofficial_extras_releases#26]
![image](https://github.com/Krappa322/arcdps_unofficial_extras_releases/assets/20342644/9c4ff809-2f33-4319-96c0-d1a82e75b5fd)

**Comment by knoxfighter** [comment]
there is a prerelease that fixes the failed injections, but it still causes crashes, i am working on a fix.

**Comment by knoxfighter** [comment]
Latest release fixes this issue (manual update might be necessary, the updater was broken as well)
