### ISSUE TITLE
Features Displayed Where?

### ISSUE THREAD

**Issue by WolfSabian** [Krappa322/arcdps_unofficial_extras_releases#3]
Maybe I'm missing something obvious, but where does it display the additional information it provides?

> Provides arcdps addons with additional information arcdps does not provide, namely:
> 
>     When players leave or join the party/squad
>     What role a player has in the squad
>     What subgroup a player is in
>     If the player is ready or not (in a squad ready check)

What window will this be in and what is the hotkey to access it?

**Comment by Krappa322** [comment]
"Provides arcdps addons" -> it's provided to other installed arcdps addons through an API. It's not visible in any in-game window

**Comment by WolfSabian** [comment]
Okay. I installed it to be able to see the killproof.me info of players in other instances, which works great, I love it.  Haven't found or figured out the other stuff yet.

**Comment by knoxfighter** [comment]
The other stuff is not yet used by any plugin, so you will not see it :)

**Comment by WolfSabian** [comment]
Oh okay, well that's good at least. I've searched through various windows and options, now I know I am not blind and can drop searching.  :)

**Comment by WolfSabian** [comment]
Thanks for the info and replies.
