### ISSUE TITLE
Initialization failed. Failed to inject hook 7

### ISSUE THREAD

**Issue by adamk33n3r** [Krappa322/arcdps_unofficial_extras_releases#4]
![image](https://user-images.githubusercontent.com/1350444/172878196-ba8c9e6e-6d4e-48e8-be5c-1f5273cfd651.png)
I noticed this started happening a couple days ago.

**Comment by knoxfighter** [comment]
Fixed with todays release

**Comment by Janitsu** [comment]
![image](https://user-images.githubusercontent.com/8763688/176547618-8ecea395-f8ed-4738-9754-5933b34bba88.png)

I am having it for some reason with (what I assume is) the newest release.
