### ISSUE TITLE
Initialization failed. Failed to inject hook 8

### ISSUE THREAD

**Issue by Jawastew** [Krappa322/arcdps_unofficial_extras_releases#6]
With the last patch unofficial extras is reporting an initialization failure:

```
Initialization failed. Reasons given:
Failed to inject hook 8
```

Running version 1.4.2.1 (see screenshot for more info)

![image](https://user-images.githubusercontent.com/20376569/182919707-2cdf2cd3-4251-4025-a51d-f6a17f6dad8c.png)

**Comment by knoxfighter** [comment]
Pre-release already done, will create a proper release this Weekend.

**Comment by knoxfighter** [comment]
Release published
