### ISSUE TITLE
Failed to inject hook 8 & 9

### ISSUE THREAD

**Issue by SappFire2008** [Krappa322/arcdps_unofficial_extras_releases#9]
Version 1.6.1.1
![eAAxOb3WZb](https://user-images.githubusercontent.com/105151052/200911916-923f1192-3d89-4409-8b37-c69504dddfcf.png)

**Comment by Jimenox** [comment]
How fix?

**Comment by knoxfighter** [comment]
Pre-release with the fix is already out, will create a proper release tonight.
